#!/bin/sh

# Set nice background.
#xsetroot -bg
feh --bg-scale ${HOME}/Bilder/wallpaper/wisconsin.jpg &
# Set nice pointer cursor.
xsetroot -cursor_name plus -fg white -bg black &

xset b off &
xset -b &
xset -dpms &
xset s noblank &
xset s off &

# Get font (sudo?) before loading xresources
xset +fp /usr/share/fonts/tamsyn-font-1.10 &
xset fp rehash &

# Keys
#xmodmap /home/marten/scripts/keys/
#setxkbmap
#./home/marten/scripts/keys/aoei

setxkbmap -layout de
xmodmap ${HOME}/scripts/keys/xmodmap_swap-caps-ctrl
#source /home/marten/scripts/keys/aoei

# Load resources.
xrdb -load ${HOME}/scripts/screens/Xresources_z3bra

xcompmgr -l 0.5 -t 0.5 -o 0.5 -r 2 -c &


# start urxvtd, xbindkeys and what not, applet , notifier

# Start window manager in the background. If it dies, X still lives.
2bwm &

# Start a terminal in the foreground. If this dies, X dies.
exec urxvt
